In [4]:
import numpy as np

In [5]:
arr = np.arange(50).reshape(10,5)

In [6]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [7]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [8]:
np.dot(arr.T, arr) 

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [9]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
np.arange(50).reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [17]:
arr3d = np.arange(50).reshape((5,5,2))
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [27]:
arr3d = np.arange(100).reshape((2,10,5))
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [44]:
arr3d.transpose(2,0,1)

array([[[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
        [50, 55, 60, 65, 70, 75, 80, 85, 90, 95]],

       [[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
        [51, 56, 61, 66, 71, 76, 81, 86, 91, 96]],

       [[ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
        [52, 57, 62, 67, 72, 77, 82, 87, 92, 97]],

       [[ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
        [53, 58, 63, 68, 73, 78, 83, 88, 93, 98]],

       [[ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
        [54, 59, 64, 69, 74, 79, 84, 89, 94, 99]]])

In [51]:
arr = np.array([[1,2,3],[5,6,7]])
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [54]:
arr.swapaxes(1,0)

array([[1, 5],
       [2, 6],
       [3, 7]])

In [56]:
arr3d.swapaxes(0,1)

array([[[ 0,  1,  2,  3,  4],
        [50, 51, 52, 53, 54]],

       [[ 5,  6,  7,  8,  9],
        [55, 56, 57, 58, 59]],

       [[10, 11, 12, 13, 14],
        [60, 61, 62, 63, 64]],

       [[15, 16, 17, 18, 19],
        [65, 66, 67, 68, 69]],

       [[20, 21, 22, 23, 24],
        [70, 71, 72, 73, 74]],

       [[25, 26, 27, 28, 29],
        [75, 76, 77, 78, 79]],

       [[30, 31, 32, 33, 34],
        [80, 81, 82, 83, 84]],

       [[35, 36, 37, 38, 39],
        [85, 86, 87, 88, 89]],

       [[40, 41, 42, 43, 44],
        [90, 91, 92, 93, 94]],

       [[45, 46, 47, 48, 49],
        [95, 96, 97, 98, 99]]])