In [1]:
import numpy as np

In [17]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# arr[0] = -1
arr2 = np.zeros(11)
np.sqrt(arr,out=arr2)
arr2

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [30]:
A = np.random.randn(10)
A

array([ 0.52935842,  0.19337487,  1.31129409, -1.60944003,  1.15817829,
       -0.58112945,  0.69181802,  1.52634074, -0.05848308, -1.12170367])

In [31]:
B = np.random.randn(10)
B

array([ 0.08110158,  2.55800808,  1.50841108,  0.02348787, -0.02993639,
        0.35800864, -0.00776568,  0.85225527, -1.26888032, -0.66834017])

In [32]:
np.add(A,B)

array([ 0.61046   ,  2.75138295,  2.81970516, -1.58595216,  1.1282419 ,
       -0.22312082,  0.68405235,  2.37859601, -1.32736339, -1.79004384])

In [33]:
np.maximum(A,B)

array([ 0.52935842,  2.55800808,  1.50841108,  0.02348787,  1.15817829,
        0.35800864,  0.69181802,  1.52634074, -0.05848308, -0.66834017])

In [36]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#3available-ufuncs'
import webbrowser as wb
wb.open(website)

True